General24
Vauhtijuoksu/wwwauhtijuoksu-cms pull request #102
Opened 2024-11-04 20:53 UTC by jiisloth

2024-11-21 06:38 UTC, Uular requested changes
Styles & templates are probably fine, some suggestions to the plugin module

2024-11-21 06:38 UTC, Uular commented on vj_cms/cms_plugins.py
> +class MobileSpeechbubble(CMSPluginBase):
Plugin names should end with `Plugin`

2024-11-21 06:38 UTC, Uular commented on vj_cms/cms_plugins.py
> +        return context
Space between classes please

2024-11-21 06:38 UTC, Uular commented on vj_cms/cms_plugins.py
> +class TweakSettings(CMSPluginBase):
Plugin names should end with `Plugin`

2024-11-21 06:38 UTC, Uular commented on vj_cms/cms_plugins.py
> +    model = TweakSettings
Model name clashes with the plugin class name – one reason to name the plugin `TweakSettingsPlugin`

2024-11-21 06:38 UTC, Uular commented on vj_cms/cms_plugins.py
> +class AnchorLink(CMSPluginBase):
Plugin names should end with `Plugin`

2024-11-21 06:38 UTC, Uular commented on vj_cms/cms_plugins.py
> +    model = AnchorLink
Model name clashes with the plugin class name – one reason to name the plugin `AnchorLinkPlugin`

2024-11-21 06:38 UTC, Uular commented on vj_cms/cms_plugins.py
> +class PriorityMessage(CMSPluginBase):
Plugin names should end with `Plugin`

2024-11-24 17:57 UTC, jiisloth commented
New generic theme

2024-11-24 17:58 UTC, merged